// <auto-generated />
namespace InscricoesOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addativochaveparticipante : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addativochaveparticipante));
        
        string IMigrationMetadata.Id
        {
            get { return "201910161637140_add-ativo-chave-participante"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
