// <auto-generated />
namespace InscricoesOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class removido_valor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removido_valor));
        
        string IMigrationMetadata.Id
        {
            get { return "201906041331186_removido_valor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
