// <auto-generated />
namespace InscricoesOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeaddativochaveparticipante : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeaddativochaveparticipante));
        
        string IMigrationMetadata.Id
        {
            get { return "201910161642208_remove-add-ativo-chave-participante"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
