namespace InscricoesOnline.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class initial : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("LIXO.TBL_INSCRICOES", "FiliadoId", "LIXO.TBL_ATLETAS");
            DropForeignKey("LIXO.TBL_ATLETAS", "EquipeId", "LIXO.TBL_EQUIPES");
            DropForeignKey("LIXO.TBL_INSCRICOES", "AcademiaId", "LIXO.TBL_EQUIPES");
            DropForeignKey("LIXO.TBL_EQUIPES", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_FAIXAS", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_MODALIDADES", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_PESO", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_CHAVE", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_INSCRICOES", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_ATLETAS", "FaixaId", "LIXO.TBL_FAIXAS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaFinal", "LIXO.TBL_FAIXAS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaInicial", "LIXO.TBL_FAIXAS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaFinal", "LIXO.TBL_FAIXAS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaInicial", "LIXO.TBL_FAIXAS");
            DropForeignKey("LIXO.TBL_CHAVE", "CategoriaFaixaId", "LIXO.TBL_CATEGORIAS_FAIXA");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaFaixaId", "LIXO.TBL_CATEGORIAS_FAIXA");
            DropForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "ModalidadeId", "LIXO.TBL_MODALIDADES");
            DropForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "ModalidadeId", "LIXO.TBL_MODALIDADES");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "ModalidadeId", "LIXO.TBL_MODALIDADES");
            DropForeignKey("LIXO.TBL_CHAVE", "ModalidadeId", "LIXO.TBL_MODALIDADES");
            DropForeignKey("LIXO.TBL_CATEGORIAS_PESO", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE");
            DropForeignKey("LIXO.TBL_CHAVE", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE");
            DropForeignKey("LIXO.TBL_CHAVE", "CategoriaLutaPesoId", "LIXO.TBL_CATEGORIAS_PESO");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaLutaPesoId", "LIXO.TBL_CATEGORIAS_PESO");
            DropForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "ChaveId", "LIXO.TBL_CHAVE");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "Chave_Id", "LIXO.TBL_CHAVE");
            DropForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "InscricaoModalidadeId", "LIXO.TBL_INSCRICOES_MODALIDADES");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "InscricaoId", "LIXO.TBL_INSCRICOES");
            DropIndex("LIXO.TBL_ATLETAS", new[] { "FaixaId" });
            DropIndex("LIXO.TBL_ATLETAS", new[] { "EquipeId" });
            DropIndex("LIXO.TBL_EQUIPES", new[] { "EventoId" });
            DropIndex("LIXO.TBL_FAIXAS", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CATEGORIAS_FAIXA", new[] { "ModalidadeId" });
            DropIndex("LIXO.TBL_CATEGORIAS_FAIXA", new[] { "FaixaIdFaixaInicial" });
            DropIndex("LIXO.TBL_CATEGORIAS_FAIXA", new[] { "FaixaIdFaixaFinal" });
            DropIndex("LIXO.TBL_CATEGORIAS_FAIXA", new[] { "EventoId" });
            DropIndex("LIXO.TBL_MODALIDADES", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CATEGORIAS_IDADE", new[] { "ModalidadeId" });
            DropIndex("LIXO.TBL_CATEGORIAS_IDADE", new[] { "FaixaIdFaixaInicial" });
            DropIndex("LIXO.TBL_CATEGORIAS_IDADE", new[] { "FaixaIdFaixaFinal" });
            DropIndex("LIXO.TBL_CATEGORIAS_IDADE", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CATEGORIAS_PESO", new[] { "CategoriaIdadeId" });
            DropIndex("LIXO.TBL_CATEGORIAS_PESO", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CHAVE_PARTICIPANTE", new[] { "ChaveId" });
            DropIndex("LIXO.TBL_CHAVE_PARTICIPANTE", new[] { "InscricaoModalidadeId" });
            DropIndex("LIXO.TBL_CHAVE_PARTICIPANTE", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CHAVE", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CHAVE", new[] { "ModalidadeId" });
            DropIndex("LIXO.TBL_CHAVE", new[] { "CategoriaFaixaId" });
            DropIndex("LIXO.TBL_CHAVE", new[] { "CategoriaIdadeId" });
            DropIndex("LIXO.TBL_CHAVE", new[] { "CategoriaLutaPesoId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "InscricaoId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "ModalidadeId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "CategoriaFaixaId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "CategoriaIdadeId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "CategoriaLutaPesoId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "EventoId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "Chave_Id" });
            DropIndex("LIXO.TBL_INSCRICOES", new[] { "EventoId" });
            DropIndex("LIXO.TBL_INSCRICOES", new[] { "AcademiaId" });
            DropIndex("LIXO.TBL_INSCRICOES", new[] { "FiliadoId" });
            DropPrimaryKey("LIXO.TBL_ATLETAS");
            DropPrimaryKey("LIXO.TBL_EQUIPES");
            DropPrimaryKey("LIXO.TBL_EVENTOS");
            DropPrimaryKey("LIXO.TBL_FAIXAS");
            DropPrimaryKey("LIXO.TBL_CATEGORIAS_FAIXA");
            DropPrimaryKey("LIXO.TBL_MODALIDADES");
            DropPrimaryKey("LIXO.TBL_CATEGORIAS_IDADE");
            DropPrimaryKey("LIXO.TBL_CATEGORIAS_PESO");
            DropPrimaryKey("LIXO.TBL_CHAVE_PARTICIPANTE");
            DropPrimaryKey("LIXO.TBL_CHAVE");
            DropPrimaryKey("LIXO.TBL_INSCRICOES_MODALIDADES");
            DropPrimaryKey("LIXO.TBL_INSCRICOES");
            AlterColumn("LIXO.TBL_ATLETAS", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_ATLETAS", "DataNascimento", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_ATLETAS", "Ativo", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_ATLETAS", "DataRegistro", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_ATLETAS", "Parataekwondo", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_ATLETAS", "FaixaId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_ATLETAS", "EquipeId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_EQUIPES", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_EQUIPES", "DataRegistro", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_EQUIPES", "EventoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_EVENTOS", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_EVENTOS", "AtivaInscricao", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_EVENTOS", "DataInicio", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_EVENTOS", "DataFim", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_EVENTOS", "DataInicioInscricoes", c => c.DateTime());
            AlterColumn("LIXO.TBL_EVENTOS", "DataFimInscricoes", c => c.DateTime());
            AlterColumn("LIXO.TBL_EVENTOS", "DataFimAlteracoes", c => c.DateTime());
            AlterColumn("LIXO.TBL_EVENTOS", "Ativo", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_FAIXAS", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_FAIXAS", "Ordem", c => c.Decimal(nullable: false, precision: 10, scale: 0));
            AlterColumn("LIXO.TBL_FAIXAS", "DataRegistro", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_FAIXAS", "EventoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "ModalidadeId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaInicial", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaFinal", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "Ativo", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "EventoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_MODALIDADES", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_MODALIDADES", "CategoriaPeso", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_MODALIDADES", "CategoriaFaixa", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_MODALIDADES", "CategoriaIdade", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_MODALIDADES", "Ranking", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_MODALIDADES", "Parataekwondo", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_MODALIDADES", "EventoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "ModalidadeId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "IdadeInicial", c => c.Decimal(nullable: false, precision: 10, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "IdadeFinal", c => c.Decimal(nullable: false, precision: 10, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaInicial", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaFinal", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "Ativo", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "EventoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "PesoInicial", c => c.Decimal(nullable: false, precision: 10, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "PesoFinal", c => c.Decimal(nullable: false, precision: 10, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "CategoriaIdadeId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "Ativo", c => c.Decimal(nullable: false, precision: 1, scale: 0));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "EventoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "ChaveId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "InscricaoModalidadeId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "Ordem", c => c.Decimal(nullable: false, precision: 10, scale: 0));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "Colocacao", c => c.Decimal(nullable: false, precision: 10, scale: 0));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "EventoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CHAVE", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_CHAVE", "EventoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CHAVE", "ModalidadeId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CHAVE", "CategoriaFaixaId", c => c.Decimal(precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CHAVE", "CategoriaIdadeId", c => c.Decimal(precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_CHAVE", "CategoriaLutaPesoId", c => c.Decimal(precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "InscricaoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "ModalidadeId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaFaixaId", c => c.Decimal(precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaIdadeId", c => c.Decimal(precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaLutaPesoId", c => c.Decimal(precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "EventoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "Chave_Id", c => c.Decimal(precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_INSCRICOES", "Id", c => c.Decimal(nullable: false, precision: 19, scale: 0, identity: true));
            AlterColumn("LIXO.TBL_INSCRICOES", "EventoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_INSCRICOES", "AcademiaId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_INSCRICOES", "FiliadoId", c => c.Decimal(nullable: false, precision: 19, scale: 0));
            AlterColumn("LIXO.TBL_INSCRICOES", "DataInscricao", c => c.DateTime(nullable: false));
            AddPrimaryKey("LIXO.TBL_ATLETAS", "Id");
            AddPrimaryKey("LIXO.TBL_EQUIPES", "Id");
            AddPrimaryKey("LIXO.TBL_EVENTOS", "Id");
            AddPrimaryKey("LIXO.TBL_FAIXAS", "Id");
            AddPrimaryKey("LIXO.TBL_CATEGORIAS_FAIXA", "Id");
            AddPrimaryKey("LIXO.TBL_MODALIDADES", "Id");
            AddPrimaryKey("LIXO.TBL_CATEGORIAS_IDADE", "Id");
            AddPrimaryKey("LIXO.TBL_CATEGORIAS_PESO", "Id");
            AddPrimaryKey("LIXO.TBL_CHAVE_PARTICIPANTE", "Id");
            AddPrimaryKey("LIXO.TBL_CHAVE", "Id");
            AddPrimaryKey("LIXO.TBL_INSCRICOES_MODALIDADES", "Id");
            AddPrimaryKey("LIXO.TBL_INSCRICOES", "Id");
            CreateIndex("LIXO.TBL_ATLETAS", "FaixaId");
            CreateIndex("LIXO.TBL_ATLETAS", "EquipeId");
            CreateIndex("LIXO.TBL_EQUIPES", "EventoId");
            CreateIndex("LIXO.TBL_FAIXAS", "EventoId");
            CreateIndex("LIXO.TBL_CATEGORIAS_FAIXA", "ModalidadeId");
            CreateIndex("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaInicial");
            CreateIndex("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaFinal");
            CreateIndex("LIXO.TBL_CATEGORIAS_FAIXA", "EventoId");
            CreateIndex("LIXO.TBL_MODALIDADES", "EventoId");
            CreateIndex("LIXO.TBL_CATEGORIAS_IDADE", "ModalidadeId");
            CreateIndex("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaInicial");
            CreateIndex("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaFinal");
            CreateIndex("LIXO.TBL_CATEGORIAS_IDADE", "EventoId");
            CreateIndex("LIXO.TBL_CATEGORIAS_PESO", "CategoriaIdadeId");
            CreateIndex("LIXO.TBL_CATEGORIAS_PESO", "EventoId");
            CreateIndex("LIXO.TBL_CHAVE_PARTICIPANTE", "ChaveId");
            CreateIndex("LIXO.TBL_CHAVE_PARTICIPANTE", "InscricaoModalidadeId");
            CreateIndex("LIXO.TBL_CHAVE_PARTICIPANTE", "EventoId");
            CreateIndex("LIXO.TBL_CHAVE", "EventoId");
            CreateIndex("LIXO.TBL_CHAVE", "ModalidadeId");
            CreateIndex("LIXO.TBL_CHAVE", "CategoriaFaixaId");
            CreateIndex("LIXO.TBL_CHAVE", "CategoriaIdadeId");
            CreateIndex("LIXO.TBL_CHAVE", "CategoriaLutaPesoId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "InscricaoId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "ModalidadeId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaFaixaId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaIdadeId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaLutaPesoId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "EventoId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "Chave_Id");
            CreateIndex("LIXO.TBL_INSCRICOES", "EventoId");
            CreateIndex("LIXO.TBL_INSCRICOES", "AcademiaId");
            CreateIndex("LIXO.TBL_INSCRICOES", "FiliadoId");
            AddForeignKey("LIXO.TBL_INSCRICOES", "FiliadoId", "LIXO.TBL_ATLETAS", "Id");
            AddForeignKey("LIXO.TBL_ATLETAS", "EquipeId", "LIXO.TBL_EQUIPES", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES", "AcademiaId", "LIXO.TBL_EQUIPES", "Id");
            AddForeignKey("LIXO.TBL_EQUIPES", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_FAIXAS", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_MODALIDADES", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_PESO", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_CHAVE", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_ATLETAS", "FaixaId", "LIXO.TBL_FAIXAS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaFinal", "LIXO.TBL_FAIXAS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaInicial", "LIXO.TBL_FAIXAS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaFinal", "LIXO.TBL_FAIXAS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaInicial", "LIXO.TBL_FAIXAS", "Id");
            AddForeignKey("LIXO.TBL_CHAVE", "CategoriaFaixaId", "LIXO.TBL_CATEGORIAS_FAIXA", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaFaixaId", "LIXO.TBL_CATEGORIAS_FAIXA", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "ModalidadeId", "LIXO.TBL_MODALIDADES", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "ModalidadeId", "LIXO.TBL_MODALIDADES", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "ModalidadeId", "LIXO.TBL_MODALIDADES", "Id");
            AddForeignKey("LIXO.TBL_CHAVE", "ModalidadeId", "LIXO.TBL_MODALIDADES", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_PESO", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE", "Id");
            AddForeignKey("LIXO.TBL_CHAVE", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE", "Id");
            AddForeignKey("LIXO.TBL_CHAVE", "CategoriaLutaPesoId", "LIXO.TBL_CATEGORIAS_PESO", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaLutaPesoId", "LIXO.TBL_CATEGORIAS_PESO", "Id");
            AddForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "ChaveId", "LIXO.TBL_CHAVE", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "Chave_Id", "LIXO.TBL_CHAVE", "Id");
            AddForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "InscricaoModalidadeId", "LIXO.TBL_INSCRICOES_MODALIDADES", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "InscricaoId", "LIXO.TBL_INSCRICOES", "Id");
        }
        
        public override void Down()
        {
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "InscricaoId", "LIXO.TBL_INSCRICOES");
            DropForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "InscricaoModalidadeId", "LIXO.TBL_INSCRICOES_MODALIDADES");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "Chave_Id", "LIXO.TBL_CHAVE");
            DropForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "ChaveId", "LIXO.TBL_CHAVE");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaLutaPesoId", "LIXO.TBL_CATEGORIAS_PESO");
            DropForeignKey("LIXO.TBL_CHAVE", "CategoriaLutaPesoId", "LIXO.TBL_CATEGORIAS_PESO");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE");
            DropForeignKey("LIXO.TBL_CHAVE", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE");
            DropForeignKey("LIXO.TBL_CATEGORIAS_PESO", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE");
            DropForeignKey("LIXO.TBL_CHAVE", "ModalidadeId", "LIXO.TBL_MODALIDADES");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "ModalidadeId", "LIXO.TBL_MODALIDADES");
            DropForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "ModalidadeId", "LIXO.TBL_MODALIDADES");
            DropForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "ModalidadeId", "LIXO.TBL_MODALIDADES");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaFaixaId", "LIXO.TBL_CATEGORIAS_FAIXA");
            DropForeignKey("LIXO.TBL_CHAVE", "CategoriaFaixaId", "LIXO.TBL_CATEGORIAS_FAIXA");
            DropForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaInicial", "LIXO.TBL_FAIXAS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaFinal", "LIXO.TBL_FAIXAS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaInicial", "LIXO.TBL_FAIXAS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaFinal", "LIXO.TBL_FAIXAS");
            DropForeignKey("LIXO.TBL_ATLETAS", "FaixaId", "LIXO.TBL_FAIXAS");
            DropForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_INSCRICOES", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_CHAVE", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_PESO", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_MODALIDADES", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_FAIXAS", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_EQUIPES", "EventoId", "LIXO.TBL_EVENTOS");
            DropForeignKey("LIXO.TBL_INSCRICOES", "AcademiaId", "LIXO.TBL_EQUIPES");
            DropForeignKey("LIXO.TBL_ATLETAS", "EquipeId", "LIXO.TBL_EQUIPES");
            DropForeignKey("LIXO.TBL_INSCRICOES", "FiliadoId", "LIXO.TBL_ATLETAS");
            DropIndex("LIXO.TBL_INSCRICOES", new[] { "FiliadoId" });
            DropIndex("LIXO.TBL_INSCRICOES", new[] { "AcademiaId" });
            DropIndex("LIXO.TBL_INSCRICOES", new[] { "EventoId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "Chave_Id" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "EventoId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "CategoriaLutaPesoId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "CategoriaIdadeId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "CategoriaFaixaId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "ModalidadeId" });
            DropIndex("LIXO.TBL_INSCRICOES_MODALIDADES", new[] { "InscricaoId" });
            DropIndex("LIXO.TBL_CHAVE", new[] { "CategoriaLutaPesoId" });
            DropIndex("LIXO.TBL_CHAVE", new[] { "CategoriaIdadeId" });
            DropIndex("LIXO.TBL_CHAVE", new[] { "CategoriaFaixaId" });
            DropIndex("LIXO.TBL_CHAVE", new[] { "ModalidadeId" });
            DropIndex("LIXO.TBL_CHAVE", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CHAVE_PARTICIPANTE", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CHAVE_PARTICIPANTE", new[] { "InscricaoModalidadeId" });
            DropIndex("LIXO.TBL_CHAVE_PARTICIPANTE", new[] { "ChaveId" });
            DropIndex("LIXO.TBL_CATEGORIAS_PESO", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CATEGORIAS_PESO", new[] { "CategoriaIdadeId" });
            DropIndex("LIXO.TBL_CATEGORIAS_IDADE", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CATEGORIAS_IDADE", new[] { "FaixaIdFaixaFinal" });
            DropIndex("LIXO.TBL_CATEGORIAS_IDADE", new[] { "FaixaIdFaixaInicial" });
            DropIndex("LIXO.TBL_CATEGORIAS_IDADE", new[] { "ModalidadeId" });
            DropIndex("LIXO.TBL_MODALIDADES", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CATEGORIAS_FAIXA", new[] { "EventoId" });
            DropIndex("LIXO.TBL_CATEGORIAS_FAIXA", new[] { "FaixaIdFaixaFinal" });
            DropIndex("LIXO.TBL_CATEGORIAS_FAIXA", new[] { "FaixaIdFaixaInicial" });
            DropIndex("LIXO.TBL_CATEGORIAS_FAIXA", new[] { "ModalidadeId" });
            DropIndex("LIXO.TBL_FAIXAS", new[] { "EventoId" });
            DropIndex("LIXO.TBL_EQUIPES", new[] { "EventoId" });
            DropIndex("LIXO.TBL_ATLETAS", new[] { "EquipeId" });
            DropIndex("LIXO.TBL_ATLETAS", new[] { "FaixaId" });
            DropPrimaryKey("LIXO.TBL_INSCRICOES");
            DropPrimaryKey("LIXO.TBL_INSCRICOES_MODALIDADES");
            DropPrimaryKey("LIXO.TBL_CHAVE");
            DropPrimaryKey("LIXO.TBL_CHAVE_PARTICIPANTE");
            DropPrimaryKey("LIXO.TBL_CATEGORIAS_PESO");
            DropPrimaryKey("LIXO.TBL_CATEGORIAS_IDADE");
            DropPrimaryKey("LIXO.TBL_MODALIDADES");
            DropPrimaryKey("LIXO.TBL_CATEGORIAS_FAIXA");
            DropPrimaryKey("LIXO.TBL_FAIXAS");
            DropPrimaryKey("LIXO.TBL_EVENTOS");
            DropPrimaryKey("LIXO.TBL_EQUIPES");
            DropPrimaryKey("LIXO.TBL_ATLETAS");
            AlterColumn("LIXO.TBL_INSCRICOES", "DataInscricao", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_INSCRICOES", "FiliadoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_INSCRICOES", "AcademiaId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_INSCRICOES", "EventoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_INSCRICOES", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "Chave_Id", c => c.Long());
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "EventoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaLutaPesoId", c => c.Long());
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaIdadeId", c => c.Long());
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaFaixaId", c => c.Long());
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "ModalidadeId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "InscricaoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_INSCRICOES_MODALIDADES", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("LIXO.TBL_CHAVE", "CategoriaLutaPesoId", c => c.Long());
            AlterColumn("LIXO.TBL_CHAVE", "CategoriaIdadeId", c => c.Long());
            AlterColumn("LIXO.TBL_CHAVE", "CategoriaFaixaId", c => c.Long());
            AlterColumn("LIXO.TBL_CHAVE", "ModalidadeId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CHAVE", "EventoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CHAVE", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "EventoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "Colocacao", c => c.Int(nullable: false));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "Ordem", c => c.Int(nullable: false));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "InscricaoModalidadeId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "ChaveId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CHAVE_PARTICIPANTE", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "EventoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "Ativo", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "CategoriaIdadeId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "PesoFinal", c => c.Int(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "PesoInicial", c => c.Int(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_PESO", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "EventoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "Ativo", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaFinal", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaInicial", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "IdadeFinal", c => c.Int(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "IdadeInicial", c => c.Int(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "ModalidadeId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_IDADE", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("LIXO.TBL_MODALIDADES", "EventoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_MODALIDADES", "Parataekwondo", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_MODALIDADES", "Ranking", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_MODALIDADES", "CategoriaIdade", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_MODALIDADES", "CategoriaFaixa", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_MODALIDADES", "CategoriaPeso", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_MODALIDADES", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "EventoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "Ativo", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaFinal", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaInicial", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "ModalidadeId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_CATEGORIAS_FAIXA", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("LIXO.TBL_FAIXAS", "EventoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_FAIXAS", "DataRegistro", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_FAIXAS", "Ordem", c => c.Int(nullable: false));
            AlterColumn("LIXO.TBL_FAIXAS", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("LIXO.TBL_EVENTOS", "Ativo", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_EVENTOS", "DataFimAlteracoes", c => c.DateTime());
            AlterColumn("LIXO.TBL_EVENTOS", "DataFimInscricoes", c => c.DateTime());
            AlterColumn("LIXO.TBL_EVENTOS", "DataInicioInscricoes", c => c.DateTime());
            AlterColumn("LIXO.TBL_EVENTOS", "DataFim", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_EVENTOS", "DataInicio", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_EVENTOS", "AtivaInscricao", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_EVENTOS", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("LIXO.TBL_EQUIPES", "EventoId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_EQUIPES", "DataRegistro", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_EQUIPES", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("LIXO.TBL_ATLETAS", "EquipeId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_ATLETAS", "FaixaId", c => c.Long(nullable: false));
            AlterColumn("LIXO.TBL_ATLETAS", "Parataekwondo", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_ATLETAS", "DataRegistro", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_ATLETAS", "Ativo", c => c.Boolean(nullable: false));
            AlterColumn("LIXO.TBL_ATLETAS", "DataNascimento", c => c.DateTime(nullable: false));
            AlterColumn("LIXO.TBL_ATLETAS", "Id", c => c.Long(nullable: false, identity: true));
            AddPrimaryKey("LIXO.TBL_INSCRICOES", "Id");
            AddPrimaryKey("LIXO.TBL_INSCRICOES_MODALIDADES", "Id");
            AddPrimaryKey("LIXO.TBL_CHAVE", "Id");
            AddPrimaryKey("LIXO.TBL_CHAVE_PARTICIPANTE", "Id");
            AddPrimaryKey("LIXO.TBL_CATEGORIAS_PESO", "Id");
            AddPrimaryKey("LIXO.TBL_CATEGORIAS_IDADE", "Id");
            AddPrimaryKey("LIXO.TBL_MODALIDADES", "Id");
            AddPrimaryKey("LIXO.TBL_CATEGORIAS_FAIXA", "Id");
            AddPrimaryKey("LIXO.TBL_FAIXAS", "Id");
            AddPrimaryKey("LIXO.TBL_EVENTOS", "Id");
            AddPrimaryKey("LIXO.TBL_EQUIPES", "Id");
            AddPrimaryKey("LIXO.TBL_ATLETAS", "Id");
            CreateIndex("LIXO.TBL_INSCRICOES", "FiliadoId");
            CreateIndex("LIXO.TBL_INSCRICOES", "AcademiaId");
            CreateIndex("LIXO.TBL_INSCRICOES", "EventoId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "Chave_Id");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "EventoId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaLutaPesoId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaIdadeId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaFaixaId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "ModalidadeId");
            CreateIndex("LIXO.TBL_INSCRICOES_MODALIDADES", "InscricaoId");
            CreateIndex("LIXO.TBL_CHAVE", "CategoriaLutaPesoId");
            CreateIndex("LIXO.TBL_CHAVE", "CategoriaIdadeId");
            CreateIndex("LIXO.TBL_CHAVE", "CategoriaFaixaId");
            CreateIndex("LIXO.TBL_CHAVE", "ModalidadeId");
            CreateIndex("LIXO.TBL_CHAVE", "EventoId");
            CreateIndex("LIXO.TBL_CHAVE_PARTICIPANTE", "EventoId");
            CreateIndex("LIXO.TBL_CHAVE_PARTICIPANTE", "InscricaoModalidadeId");
            CreateIndex("LIXO.TBL_CHAVE_PARTICIPANTE", "ChaveId");
            CreateIndex("LIXO.TBL_CATEGORIAS_PESO", "EventoId");
            CreateIndex("LIXO.TBL_CATEGORIAS_PESO", "CategoriaIdadeId");
            CreateIndex("LIXO.TBL_CATEGORIAS_IDADE", "EventoId");
            CreateIndex("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaFinal");
            CreateIndex("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaInicial");
            CreateIndex("LIXO.TBL_CATEGORIAS_IDADE", "ModalidadeId");
            CreateIndex("LIXO.TBL_MODALIDADES", "EventoId");
            CreateIndex("LIXO.TBL_CATEGORIAS_FAIXA", "EventoId");
            CreateIndex("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaFinal");
            CreateIndex("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaInicial");
            CreateIndex("LIXO.TBL_CATEGORIAS_FAIXA", "ModalidadeId");
            CreateIndex("LIXO.TBL_FAIXAS", "EventoId");
            CreateIndex("LIXO.TBL_EQUIPES", "EventoId");
            CreateIndex("LIXO.TBL_ATLETAS", "EquipeId");
            CreateIndex("LIXO.TBL_ATLETAS", "FaixaId");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "InscricaoId", "LIXO.TBL_INSCRICOES", "Id");
            AddForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "InscricaoModalidadeId", "LIXO.TBL_INSCRICOES_MODALIDADES", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "Chave_Id", "LIXO.TBL_CHAVE", "Id");
            AddForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "ChaveId", "LIXO.TBL_CHAVE", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaLutaPesoId", "LIXO.TBL_CATEGORIAS_PESO", "Id");
            AddForeignKey("LIXO.TBL_CHAVE", "CategoriaLutaPesoId", "LIXO.TBL_CATEGORIAS_PESO", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE", "Id");
            AddForeignKey("LIXO.TBL_CHAVE", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_PESO", "CategoriaIdadeId", "LIXO.TBL_CATEGORIAS_IDADE", "Id");
            AddForeignKey("LIXO.TBL_CHAVE", "ModalidadeId", "LIXO.TBL_MODALIDADES", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "ModalidadeId", "LIXO.TBL_MODALIDADES", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "ModalidadeId", "LIXO.TBL_MODALIDADES", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "ModalidadeId", "LIXO.TBL_MODALIDADES", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "CategoriaFaixaId", "LIXO.TBL_CATEGORIAS_FAIXA", "Id");
            AddForeignKey("LIXO.TBL_CHAVE", "CategoriaFaixaId", "LIXO.TBL_CATEGORIAS_FAIXA", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaInicial", "LIXO.TBL_FAIXAS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "FaixaIdFaixaFinal", "LIXO.TBL_FAIXAS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaInicial", "LIXO.TBL_FAIXAS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "FaixaIdFaixaFinal", "LIXO.TBL_FAIXAS", "Id");
            AddForeignKey("LIXO.TBL_ATLETAS", "FaixaId", "LIXO.TBL_FAIXAS", "Id");
            AddForeignKey("LIXO.TBL_CHAVE_PARTICIPANTE", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES_MODALIDADES", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_CHAVE", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_PESO", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_IDADE", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_MODALIDADES", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_CATEGORIAS_FAIXA", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_FAIXAS", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_EQUIPES", "EventoId", "LIXO.TBL_EVENTOS", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES", "AcademiaId", "LIXO.TBL_EQUIPES", "Id");
            AddForeignKey("LIXO.TBL_ATLETAS", "EquipeId", "LIXO.TBL_EQUIPES", "Id");
            AddForeignKey("LIXO.TBL_INSCRICOES", "FiliadoId", "LIXO.TBL_ATLETAS", "Id");
        }
    }
}
